### ISSUE TITLE
(Github Comment Enhancer) Keyboard shortcuts

### ISSUE THREAD

**Issue by jerone** [jerone/UserScripts#19]
~~https://github.com/ccampbell/mousetrap~~
~~https://github.com/jeresig/jquery.hotkeys~~

**Comment by thomaslevesque** [comment]
:+1:

**Comment by jerone** [comment]
Took me some time to figure out, but I think I've got the shortcuts working great now.

The following shortcuts are supported:
* Bold = <kbd>ctrl+b</kbd>
* Italic = <kbd>ctrl+i</kbd>
* Underline = <kbd>ctrl+u</kbd>
* Strikethrough = <kbd>ctrl+s</kbd>
* Header 1 = <kbd>ctrl+1</kbd>
* Header 2 = <kbd>ctrl+2</kbd>
* Header 3 = <kbd>ctrl+3</kbd>
* Header 4 = <kbd>ctrl+4</kbd>
* Header 5 = <kbd>ctrl+5</kbd>
* Header 6 = <kbd>ctrl+6</kbd>
* Link = <kbd>ctrl+shift+w</kbd>
* Image = <kbd>ctrl+shift+i</kbd>
* Unordered List = <kbd>ctrl+shift+u</kbd>
* Ordered List = <kbd>ctrl+shift+o</kbd>
* Task List = <kbd>ctrl+shift+t</kbd>
* Code = <kbd>ctrl+c</kbd>
* Quote = <kbd>ctrl+q</kbd>
* Line = <kbd>ctrl+l</kbd>
* Table = <kbd>ctrl+t</kbd>
* Clear = <kbd>ctrl+shift+x</kbd>

I'm not releasing this feature just yet, but if anyone interested you can try the development version: https://github.com/jerone/UserScripts/tree/Github_Comment_Enhancer/Github_Comment_Enhancer

**Comment by thomaslevesque** [comment]
Awesome! I was considering trying to do it myself, but I'm not proficient in Javascript so I'm not sure I would have succeeded...

I noticed that some of the shortcuts you picked conflict with pre-defined browser shortcuts, which should be avoided if possible:

- <kbd>ctrl+c</kbd> is traditionally reserved for "Copy", so it's probably not a good idea... Stackoverflow uses <kbd>ctrl+k</kbd>, which seems a good choice to me
- <kbd>ctrl+s</kbd> is mapped to "Save" in most browsers 
- <kbd>ctrl+t</kbd> is mapped to "New tab" in most browsers
- <kbd>ctrl+shift+t</kbd> is mapped to "Reopen closed tab" in most browsers

Also, I don't think that we need a shortcut for each and every command, just for the most common. For instance, to write a horizontal line you just need to type "***", so the shortcut isn't very useful; I'd rather have <kbd>ctrl+l</kbd> be used for Link (as on Stackoverflow), because it's more obvious than <kbd>ctrl+shift+w</kbd>, and not have any shortcut for Line.

**Comment by jerone** [comment]
Thank you for your feedback!

> I noticed that some of the shortcuts you picked conflict with pre-defined browser shortcuts, which should be avoided if possible:

All shortcuts are caught in only the comment fields, where the default behavior is prevented. For example <kbd>ctrl+s</kbd> won't open the save dialog for the page when pressed in the comment field.

> <kbd>ctrl+c</kbd> is traditionally reserved for "Copy", so it's probably not a good idea... Stackoverflow uses <kbd>ctrl+k</kbd>, which seems a good choice to me

Should have seen that! 

> I'd rather have <kbd>ctrl+l</kbd> be used for Link (as on Stackoverflow) [...]

Good suggestion to look at StackOverflow, didn't know they had shortcuts too.

I've updated above list with the new shortcuts.

**Comment by thomaslevesque** [comment]
Perfect !

And thanks for writing this script, it makes writing on Github so much easier

**Comment by jerone** [comment]
Thanks for using! I've got [more userscript for GitHub](https://github.com/jerone/UserScripts#github) that make things just a bit easier.

If you've got other features or feedback, feel free to open an issue.

**Comment by thomaslevesque** [comment]
Is the user script supposed to work on Chrome as well? It shows the buttons, but they don't do anything and the keyboard shortcuts don't work.

**Comment by thomaslevesque** [comment]
If I use Tampermonkey to install the script, the buttons work, but the shortcuts don't

**Comment by jerone** [comment]
Thanks for testing! There were some issues with Chrome that needed attention. One of those issues resulted in new shortcuts. I have updated [above list](https://github.com/jerone/UserScripts/issues/19#issuecomment-96382852) with the new combinations.

**Comment by thomaslevesque** [comment]
_Yes_, **it** `works` :+1: 

Thanks!

**Comment by jerone** [comment]
[**@thomaslevesque**](https://github.com/thomaslevesque) commented on [27 apr. 2015 17:52 CEST](https://github.com/jerone/UserScripts/issues/19#issuecomment-96720927 "2015-04-27T15:52:52Z - Replied by Github Comment Enhancer"):
> _Yes_, **it** `works` :+1: 

Haha

The only one I'm not happy with is table <kbd>alt+shift+t</kbd>. But both <kbd>ctrl+t</kbd> & <kbd>ctrl+shift+t</kbd> can't be overridden in Chrome.
