### ISSUE TITLE
(Github Comment Enhancer) Missing emoticon button

### ISSUE THREAD

**Issue by Mte90** [jerone/UserScripts#37]
Add a dropdown menu for choose the emoticon.

**Comment by jerone** [comment]
Thnx for the RFE. 

I actually looked at this earlier, hoping for a drag&drop solution like https://github.com/johannhof/emoji-helper

**Comment by jerone** [comment]
It's not perfect, but it's a start. Will try it for a few days before releasing. One can always download the development version: https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer

**Comment by jerone** [comment]
![2015_03_21_14_40_31_github_comment_enhancer_missing_emoticon_button_issue_37_jerone_userscrip](https://cloud.githubusercontent.com/assets/55841/6765257/8211416a-cfd8-11e4-98c6-62b4ba9cdf9c.png)

**Comment by Mte90** [comment]
:blush: :smiley: :+1:
works very well :-D

**Comment by jerone** [comment]
@Mte90 commented on [21 mrt. 2015 16:20 CET](https://github.com/jerone/UserScripts/issues/37#issuecomment-84371522 "2015-03-21T15:20:14Z - Replied by Github Comment Enhancer"):
> :blush: :smiley: :+1:
> works very well :-D

Thnx! :smile: 

Still thinking about some improvements:
* [ ] First time opening is slow.
* [ ] Not sure about the button icon. There's no emoji icon available in [Octicons](https://github.com/github/octicons) however.
* [ ] Searching doesn't take `data-text` into account.
* [ ] Getting the list is still a little hacky.
* [ ] Not tested on [all test cases](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer#notes).
* [ ] Not tested on [other Userscript addons](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer#compatible).
* [ ] Thinking about an inline list, instead of a vertical list. Maybe tooltips for the emoji name.
* [ ] There's no big overview. Maybe linking to http://www.emoji-cheat-sheet.com
